name:                 funkprog-project
version:              0.1.0.0
visibility:           public
id:                   funkprog-project-0.1.0.0-IYN8FT3ybYE8ZGGR3Clfcm
key:                  funkprog-project-0.1.0.0-IYN8FT3ybYE8ZGGR3Clfcm
synopsis:             Algoritamska glazbena kompozicija
description:
    Algoritamska glazbena kompozicija s genetskim algoritmima i zadovoljenjem ograničenja u Haskellu.

abi:                  31d1372192f0b533cc5a2abd8eae1ade
exposed:              True
exposed-modules:      Constraint Genetic
hidden-modules:       Paths_funkprog_project
import-dirs:
    "C:\\Users\\Abra PC\\funkprog-project base\\funkprog-project\\.stack-work\\install\\e0fe9be0\\lib\\x86_64-windows-ghc-9.4.7\\funkprog-project-0.1.0.0-IYN8FT3ybYE8ZGGR3Clfcm"

library-dirs:
    "C:\\Users\\Abra PC\\funkprog-project base\\funkprog-project\\.stack-work\\install\\e0fe9be0\\lib\\x86_64-windows-ghc-9.4.7\\funkprog-project-0.1.0.0-IYN8FT3ybYE8ZGGR3Clfcm"
    D:\FAKS_REMOTE\stack-programs\x86_64-windows\msys2-20240727\mingw64\lib
    D:\FAKS_REMOTE\stack-programs\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    "C:\\Users\\Abra PC\\funkprog-project base\\funkprog-project\\.stack-work\\install\\e0fe9be0\\lib\\x86_64-windows-ghc-9.4.7\\funkprog-project-0.1.0.0-IYN8FT3ybYE8ZGGR3Clfcm"
    D:\FAKS_REMOTE\stack-programs\x86_64-windows\msys2-20240727\mingw64\lib
    D:\FAKS_REMOTE\stack-programs\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    "C:\\Users\\Abra PC\\funkprog-project base\\funkprog-project\\.stack-work\\install\\e0fe9be0\\lib\\x86_64-windows-ghc-9.4.7"
    D:\FAKS_REMOTE\stack-programs\x86_64-windows\msys2-20240727\mingw64\lib
    D:\FAKS_REMOTE\stack-programs\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    "C:\\Users\\Abra PC\\funkprog-project base\\funkprog-project\\.stack-work\\install\\e0fe9be0\\share\\x86_64-windows-ghc-9.4.7\\funkprog-project-0.1.0.0"

hs-libraries:         HSfunkprog-project-0.1.0.0-IYN8FT3ybYE8ZGGR3Clfcm
include-dirs:
    D:\FAKS_REMOTE\stack-programs\x86_64-windows\msys2-20240727\mingw64\include

depends:
    Euterpea-2.0.7-89alUIxQkol730jcYPsLsY
    HCodecs-0.5.2-1ZyDBDJMaQy5YTouRJZ5RU base-4.17.2.0
    midi-0.2.2.4-7a5i559svdpLQg6D9uryTH
    random-1.2.1.1-18TX09hUOZxBsw2Og1xFjq
    sbv-10.9-HbLncmzZu6u2xmNtCYJoC5

haddock-interfaces:
    "C:\\Users\\Abra PC\\funkprog-project base\\funkprog-project\\.stack-work\\install\\e0fe9be0\\doc\\funkprog-project-0.1.0.0\\funkprog-project.haddock"

haddock-html:
    "C:\\Users\\Abra PC\\funkprog-project base\\funkprog-project\\.stack-work\\install\\e0fe9be0\\doc\\funkprog-project-0.1.0.0"
